### ISSUE TITLE
test run failed

### ISSUE THREAD

**Issue by zxlamtlh** [guzhaoyuan/snake_robot#2]
After following the steps of the project, we can't run it successfully because of some program error.
Error one: Can not compile successfully after cloning that three packages. 
                Maybe some packages can not be found.
Error one: Some nodes run unsuccessfully.

**Comment by guzhaoyuan** [comment]
Can you provide more detailed information about the compile error?

**Comment by zxlamtlh** [comment]
After modifying ./brash file，we have solved the problem. I am also a noob in using ROS,you can send e-mail to the guzhaoyuan.--    发自新浪邮箱客户端
在 7月17日 11:48，Zhaoyuan Gu <notifications@github.com> 写道：

Can you provide more detailed information about the compile error?

&mdash;

**Comment by guzhaoyuan** [comment]
I am glad you figured it out!
